apiVersion: v1
kind: Pod
metadata:
  name: director-api-pod
  labels:
    app: director-api-pod
spec:
  containers:
    - name: director-api-pod
      image: registry.hub.docker.com/kaanaydemir0/director-api
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8082
      env:
        - name: SPRING_DATA_MONGODB_HOST
          value: mongodb-service
        - name: SPRING_DATA_MONGODB_PORT
          value: "27017"
        - name: SPRING_DATA_MONGODB_DATABASE
          value: director
        - name: SPRING_DATA_MONGODB_USERNAME
          value: director
        - name: SPRING_DATA_MONGODB_PASSWORD
          value: director
        - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
          value: admin
        - name: SPRING_DATA_MONGODB_AUTOINDEX_CREATION
          value: "true"
  restartPolicy: Always
  