apiVersion: v1
kind: Service
metadata:
  name: director-api-service
spec:
  selector:
    app: director-api-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
      nodePort: 30003
  type: NodePort
  