apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
  labels:
    app: mongodb-pod
spec:
  containers:
    - name: mongodb-pod
      image: mongo
      imagePullPolicy: IfNotPresent
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: director
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: director
        - name: MONGO_INITDB_DATABASE
          value: director
      ports:
        - containerPort: 27017
    - name: mongo-express-pod
      image: mongo-express
      imagePullPolicy: IfNotPresent
      env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: director
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: director
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongodb-pod
        - name: ME_CONFIG_MONGODB_PORT
          value: "27017"
      ports:
        - containerPort: 8081
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
      app: mongodb-pod
  ports:
      - protocol: TCP
        port: 27017
        targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongodb-pod
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30002
  type: NodePort
  